### ISSUE TITLE
bands argument instead of colors driving bands

### ISSUE THREAD

**Issue by timelyportfolio** [kmandov/d3-horizon-chart#5]
Thanks so much for doing this; `d3-horizon-chart` is incredibly helpful!  I have integrated in an `R` [`htmlwidget`](http://htmlwidgets.org) called [`d3horizonR`](https://timelyportfolio.github.io).  `colors` as a driver of n `bands` works fine, but I very much like the explicit `bands` argument with just the outer colors as in the `horizon` d3-plugin (adapted to `d3v4` [here](https://github.com/timelyportfolio/d3-horizon)).  I am happy to submit pull but wanted to make sure you agreed with the change before expending the effort.

Thanks again!

**Comment by kmandov** [comment]
Thanks for the effort @timelyportfolio! 
I was also thinking about an explicit bands argument - it seems natural to have such an argument. However after some thinking I chose the simpler approach of using the colors argument only - this is the way @mbostock implemented [Horizon](https://github.com/square/cubism/wiki/Horizon#colors) in cubism.js at the first place.  
It makes sense, because the number of bands is always based on the number of colors. If you add an explicit bands argument you need to make sure that bands and colors stay in sync.

Best regards!

**Comment by timelyportfolio** [comment]
Fair enough, and I understand.  However, I thought I would point to the lines https://github.com/timelyportfolio/d3-horizon/blob/master/src/horizon.js#L17-L19 and https://github.com/timelyportfolio/d3-horizon/blob/master/src/horizon.js#L127 in the other Mike Bostock/Jason Davies horizon plugin that keep the colors and bands in sync.  I might still play a little with alternate color/band specifications, but I will refrain from any pull requests :)

Thanks again for your work on this!  I think the R community has already started adopting it.

**Comment by kmandov** [comment]
The R plug-in looks great! I'll try it out the next time I need horizon charts in R.
I do agree that using the bands argument makes perfect sense and keeping colors and bands in sync is not such of an issue. I'll keep that in mind for the next versions of d3-horizon-chart.

Thank you for the contribution!
